#mongodb

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
#      database: Document
    web:
      pageable:
        default-page-size: 10
        default-page: 0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com