version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  mongo-backup:
    image: mongo
    volumes:
      - mongo-backup-data:/backup
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    deploy:
      replicas: 2

  studadvice-back:
    image: studadvice
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
#  studadvice-back:
#    image: ghcr.io/studadvice/studadvice
#    ports:
#      - "8080:8080"
#    deploy:
#      replicas: 3
#    dns:
#      - 8.8.8.8
#      - 8.8.4.4
#    environment:
#      SPRING_DATA_MONGODB_HOST: mongo
#      SPRING_DATA_MONGODB_PORT: 27017

  studadvice-backoffice:
    image: ghcr.io/studadvice/studadvice_backoffice
    ports:
      - "4200:80"
    deploy:
      replicas: 3

volumes:
  mongo-data:
  mongo-backup-data: