version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  mongo-backup:
    image: mongo
    volumes:
      - mongo-backup-data:/backup
    command: >
      /bin/bash -c 
      "while true; do 
        mongodump --host mongo --out /backup/$(date +\%Y-\%m-\%dT\%H:\%M:\%S) && 
        sleep 86400; 
      done"
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    deploy:
      replicas: 2
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  studadvice-back:
    image: ghcr.io/studadvice/studadvice
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017

  studadvice-backoffice:
    image: ghcr.io/studadvice/studadvice_backoffice
    ports:
      - "4200:80"
    deploy:
      replicas: 3

volumes:
  mongo-data:
  mongo-backup-data: