name: 'Setup Common Environment'
description: 'Setup common environment variables for Firebase and Maven'
runs:
  using: 'composite'
  steps:
    - run: echo "${{ secrets.FIREBASE_CONFIG_BASE64 }}" | base64 -d > ${{ github.workspace }}/firebase-config.json
      shell: bash
    - run: echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/firebase-config.json" >> $GITHUB_ENV
      shell: bash
