name: Studadvice Maven CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common-env
        with:
          firebase-config-base64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
      - name: Cache Maven Packages
        uses: ./.github/actions/cache-maven-packages

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common-env
        with:
          firebase-config-base64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
      - name: Cache Maven Packages
        uses: ./.github/actions/cache-maven-packages

      - name: Analyse with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=studadvice_studadvice-back

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common-env
        with:
          firebase-config-base64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
      - name: Cache Maven Packages
        uses: ./.github/actions/cache-maven-packages

      - name: Test
        run: mvn -B test -Punit-tests

  test-integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Common Environment
        uses: ./.github/actions/setup-common-env
        with:
          firebase-config-base64: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          java-version: '17'
      - name: Cache Maven Packages
        uses: ./.github/actions/cache-maven-packages

      - name: Test
        run: mvn -B test -Pintegration-tests

  build_image:
    runs-on: ubuntu-latest
    needs:
      - test-unit
      - test-integration
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-common-env

      - name: Build Image Docker
        run: |
          docker build --build-arg FIREBASE_CONFIG_PATH=firebase-config.json -t studadvice:${{ github.sha }} .
          docker tag studadvice:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/studadvice:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.STUDADVICE_BACK_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/studadvice:latest
