name: Studadvice Maven CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Common Environment
        run: |
          echo "${{ secrets.FIREBASE_CONFIG_BASE64 }}" | base64 -d > firebase-config.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-config.json" >> $GITHUB_ENV
          echo "JAVA_VERSION=17" >> $GITHUB_ENV
          echo "MAVEN_CACHE_DIR=~/.m2" >> $GITHUB_ENV

      - name: Set up & cache Temurin JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'adopt'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ${{ env.MAVEN_CACHE_DIR }}
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

  analyse:
    name: Analyse
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-common-env
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/cache-maven-packages

      - name: Analyse with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=studadvice_studadvice-back

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: analyse
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-common-env
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/cache-maven-packages

      - name: Test
        run: mvn -B test

  build_image:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-common-env

      - name: Build Image Docker
        run: |
          docker build --build-arg FIREBASE_CONFIG_PATH=firebase-config.json -t studadvice:${{ github.sha }} .
          docker tag studadvice:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/studadvice:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.STUDADVICE_BACK_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/studadvice:latest
