name: Deploy to VPS

on:
  workflow_run:
    workflows: [ "Studadvice Maven CI" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH and Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          debug: true
          script: |
            echo ${{ secrets.STUDADVICE_BACK_TOKEN }} | sudo docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            sudo docker pull ghcr.io/${{ github.repository_owner }}/studadvice:latest
            sudo docker stack deploy --compose-file docker-compose.yml studadvice
            sudo docker service update --image ghcr.io/studadvice/studadvice --force studadvice_studadvice-back
