name: Studadvice maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2


    - name: Build with Maven
      run: mvn compile

    - name: Test with Maven
      run: mvn test

    - name: Package with Maven
      run: mvn package -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: studadvice
        path: target/studadvice-0.0.1-SNAPSHOT.jar